-- 20 clearly labeled fictional sample jobs; no real employer or salary claims.
-- Idempotent. Only the existing Medosha Samples profile is used.
begin;
with sample(n,title,category,city,kind,experience,description,requirements,skills) as (values
(1,'Site Engineer – Apartment Construction','site_engineering','Addis Ababa','full_time','mid','Coordinate daily concrete, masonry and subcontractor work on a residential apartment project. Maintain site diaries, inspection requests and progress quantities.','Civil engineering degree; 3+ years of site experience; ability to read structural drawings.','AutoCAD,Site supervision,Concrete works'),
(2,'Architect – Residential Design','architecture','Addis Ababa','full_time','mid','Develop residential layouts, elevations and coordinated drawing packages. Prepare revisions from client feedback and check room circulation and dimensions.','Architecture qualification; 3+ years of experience; residential portfolio.','Revit,AutoCAD,Residential design'),
(3,'Junior CAD Draftsperson','drafting_cad','Adama','full_time','junior','Prepare measured plans, drawing revisions and as-built documentation under an architect. Keep drawing numbers and revisions organized.','Relevant diploma or degree; 1+ year of drafting experience; sample drawing sheets.','AutoCAD,Drawing standards,As-built drawings'),
(4,'Interior Designer – Apartment Renovations','interior_design','Addis Ababa','contract','mid','Design practical apartment interiors including finishes, lighting layouts and fitted furniture. Produce specifications and coordinate site measurements.','Interior design or architecture background; completed residential portfolio; 2+ years of experience.','Space planning,SketchUp,Material specification'),
(5,'Quantity Surveyor – BOQ and Valuations','quantity_surveying','Bishoftu','full_time','mid','Measure building works from drawings, prepare BOQs and review interim valuations. Maintain variation and material reconciliation records.','Quantity surveying or civil engineering qualification; 3+ years of experience.','Excel,Quantity takeoff,BOQ'),
(6,'Structural Engineer – Residential Buildings','structural_engineering','Addis Ababa','contract','senior','Prepare structural models, calculations and reinforcement drawings for residential buildings. Coordinate architectural changes and respond to site technical queries.','Structural or civil engineering degree; 5+ years of relevant design experience; applicable professional credentials.','ETABS,SAFE,Reinforced concrete'),
(7,'Electrical Installation Technician','electrical','Hawassa','contract','mid','Install conduits, cables, distribution boards and lighting for a building fit-out. Follow approved drawings and document testing before handover.','Relevant electrical training; 3+ years of installation experience; safe isolation knowledge.','Wiring,Electrical testing,Drawing interpretation'),
(8,'Plumber – Residential Fit-Out','plumbing','Addis Ababa','contract','mid','Install water supply, drainage and bathroom fixtures. Carry out pressure and leakage tests and coordinate concealed services with finishing teams.','Plumbing training or equivalent trade experience; 3+ years of work on buildings.','PPR piping,Drainage,Pressure testing'),
(9,'MDF Cabinet Maker and Installer','carpentry','Addis Ababa','full_time','mid','Fabricate and install wardrobes and kitchens from workshop drawings. Check cut lists, edge banding, hinges, drawer runners and site fit.','3+ years of cabinet fabrication experience; ability to read millimetre dimensions and operate workshop equipment safely.','MDF fabrication,Edge banding,Cabinet installation'),
(10,'Gypsum Ceiling Installer','finishing','Adama','contract','mid','Set out suspended ceilings and install framing, boards and access panels. Coordinate light openings and finish joints ready for painting.','2+ years of gypsum ceiling experience; ability to follow reflected ceiling plans.','Gypsum board,Ceiling framing,Joint finishing'),
(11,'Ceramic and Porcelain Tile Installer','tiling','Addis Ababa','contract','mid','Lay wall and floor tiles in bathrooms and kitchens. Check substrate preparation, wet-area falls, alignment and grout finish.','3+ years of tiling experience; wet-area installation portfolio or references.','Tile setting,Substrate preparation,Grouting'),
(12,'Painter – Interior Finishing','painting','Bishoftu','temporary','mid','Prepare walls, repair minor surface defects and apply primer and finish coats. Protect adjoining surfaces and maintain consistent colour and coverage.','2+ years of finishing experience; familiarity with surface preparation and safe access.','Surface preparation,Interior paint,Quality control'),
(13,'Steel Fabricator – Gates and Railings','steel_fabrication','Addis Ababa','full_time','mid','Measure, fabricate and fit steel gates and stair railings. Follow workshop drawings, check weld quality and prepare surfaces for coating.','3+ years of fabrication experience; safe welding and cutting practices.','Welding,Steel fabrication,Site measurement'),
(14,'Land Surveyor – Building Setting-Out','surveying','Adama','contract','mid','Establish control points, set out building grids and verify levels. Prepare survey records and coordinate checks before concrete work.','Surveying qualification; 3+ years of experience using total stations and levels.','Total station,Levelling,Setting out'),
(15,'Construction Project Manager','project_management','Addis Ababa','full_time','senior','Lead programme coordination, subcontractor meetings and site reporting for a residential project. Monitor procurement, variations, quality and project risks.','Construction-related degree; 7+ years of experience with project delivery responsibility.','MS Project,Contract administration,Team leadership'),
(16,'Procurement Officer – Building Materials','procurement','Addis Ababa','full_time','mid','Compare supplier quotations, prepare purchase requests and track deliveries. Verify material specifications with technical teams and maintain procurement records.','Business, supply-chain or construction qualification; 3+ years of procurement experience.','Supplier sourcing,Excel,Purchase orders'),
(17,'3D Architectural Visualizer','visualization_3d','Addis Ababa','freelance','mid','Produce exterior and interior images from supplied architectural models. Follow the approved geometry, material references and agreed revision scope.','Strong architectural visualization portfolio; ability to organize source files and meet milestones.','SketchUp,Blender,Enscape'),
(18,'BIM Modeler – Building Coordination','bim','Addis Ababa','full_time','mid','Build and maintain coordinated architectural models, sheets and schedules. Resolve model issues with the design team and maintain consistent BIM standards.','3+ years of Revit experience; coordinated building-model portfolio.','Revit,BIM coordination,Drawing production'),
(19,'Landscape Designer – Residential Compound','landscaping','Hawassa','freelance','mid','Prepare a compact compound landscape plan including paths, planting and drainage coordination. Specify maintainable planting suited to the site and prepare quantities.','Landscape or related design experience; site planning portfolio; knowledge of local planting.','Landscape design,Site planning,Planting schedules'),
(20,'Graduate Civil Engineering Intern','civil_engineering','Addis Ababa','internship','entry','Assist a site team with measurement records, drawing registers and supervised quality checks. Learn reporting and construction coordination under an assigned engineer.','Recent civil engineering graduate; basic Excel and AutoCAD skills; willingness to learn site procedures.','Excel,AutoCAD,Site documentation')
)
insert into public.jobs (id,poster_id,title,slug,description,responsibilities,requirements,category,location_city,job_type,experience_level,work_mode,skills,status,visibility,salary_visible)
select md5('medosha:jobs-sample-20261003:'||n)::uuid,
(select id from public.profiles where username='medosha_samples'),
'[SAMPLE / ናሙና] '||title , 'medosha-sample-job-20261003-'||n,
'SAMPLE / ናሙና — Fictional example for exploring Medosha, not a verified vacancy. Do not submit an application or personal documents.\n\n'||description,
description,requirements,category,city,kind::public.job_type,experience::public.experience_level,
(case when category='visualization_3d' then 'remote' when category in ('architecture','interior_design','bim','landscaping','structural_engineering') then 'hybrid' else 'on_site' end)::public.work_mode,
string_to_array(skills,','),'open','public',false
from sample on conflict (id) do nothing;
select count(*) as sample_jobs from public.jobs where slug like 'medosha-sample-job-20261003-%';
commit;
