/**
 * Placing a property from the name of a neighbourhood.
 *
 *   npm run check:map
 *
 * One rule matters more than the rest: **a location that cannot be identified
 * gets no coordinate.** A property in the list with no pin is a small gap. A
 * property pinned in the wrong part of Addis is a buyer driving to Kolfe for a
 * flat in Bole, and nothing on the screen would have warned them.
 *
 * The second rule is that the two copies of the gazetteer agree. The seed is
 * generated by Python, which cannot import TypeScript, so the table is written
 * twice. Two copies that drift are worse than one copy that is wrong, because
 * the map and the seed would then disagree about where a property is.
 */

import { readFileSync } from "node:fs";

// Set before the module under test reads it. `safe-src` resolves the allowed
// host from this variable, so the check has to name one.
process.env.NEXT_PUBLIC_SUPABASE_URL = "https://abc123.supabase.co";

import {
  APPROXIMATE_NOTE,
  findNeighbourhood,
  isLocationAccuracy,
  knownNeighbourhoods,
  LOCATION_ACCURACIES,
  scatterWithin,
} from "../src/lib/location/addis-neighbourhoods.ts";
import { isRenderableSrc, safeImageSrc } from "../src/lib/images/safe-src.ts";
import { listingBadges } from "../src/lib/property/listing.ts";

const GREEN = "[32m";
const RED = "[31m";
const DIM = "[2m";
const RESET = "[0m";

let passed = 0;
const failures: string[] = [];

function check(name: string, condition: boolean, detail = "") {
  if (condition) {
    passed += 1;
    return;
  }
  failures.push(`${name}${detail ? ` — ${detail}` : ""}`);
}

// ---------------------------------------------------------------------------
// 1. Addis Ababa is where Addis Ababa is
//
// A transposed pair of coordinates, or a sign flip, puts the whole city in the
// Indian Ocean and every marker with it. Cheap to assert, and the kind of
// mistake that is invisible in a table of numbers.
// ---------------------------------------------------------------------------

/** The default in `scatterWithin`. Kept here so the two assertions agree. */
const SCATTER_RADIUS_M = 150;

const BOX = { south: 8.85, north: 9.15, west: 38.6, east: 39.0 };

for (const place of knownNeighbourhoods()) {
  check(
    `${place.name} is inside Addis Ababa`,
    place.latitude > BOX.south &&
      place.latitude < BOX.north &&
      place.longitude > BOX.west &&
      place.longitude < BOX.east,
    `${place.latitude}, ${place.longitude}`,
  );
}

check(
  "no two neighbourhoods share a point",
  new Set(knownNeighbourhoods().map((p) => `${p.latitude},${p.longitude}`)).size ===
    knownNeighbourhoods().length,
);

// ---------------------------------------------------------------------------
// 2. An unknown place gets no coordinate
// ---------------------------------------------------------------------------

for (const nonsense of [
  "",
  "   ",
  "Atlantis",
  "Manchester",
  "qwertyuiop",
  "123456",
  "Somewhere in the countryside",
]) {
  check(
    `"${nonsense}" is not located`,
    findNeighbourhood(nonsense) === null,
    `${findNeighbourhood(nonsense)?.name}`,
  );
}

// ---------------------------------------------------------------------------
// 3. The longest name wins
//
// "Summit Condo, Bole" contains both Summit and Bole. They are 7 km apart, and
// the specific one is the one the writer meant. Getting this backwards is the
// single most likely way to put a property in the wrong place while every
// coordinate in the table is correct.
// ---------------------------------------------------------------------------

check(
  "Summit Condo, Bole is in Summit, not Bole",
  findNeighbourhood("Summit Condo, Bole")?.name === "Summit",
  `${findNeighbourhood("Summit Condo, Bole")?.name}`,
);
check(
  "Bole Medhanialem is not merely Bole",
  findNeighbourhood("Bole Medhanialem")?.name === "Bole Medhanialem",
  `${findNeighbourhood("Bole Medhanialem")?.name}`,
);
check(
  "Bole Wollo Sefer is not merely Bole",
  findNeighbourhood("Bole Wollo Sefer")?.name === "Bole Wollo Sefer",
);
check(
  "Gerji Imperial is not merely Gerji",
  findNeighbourhood("Gerji Imperial")?.name === "Gerji Imperial",
);
check(
  "plain Bole is still Bole",
  findNeighbourhood("Bole")?.name === "Bole",
);
check(
  "Lebu Haile Garment is not merely Lebu",
  findNeighbourhood("Lebu Haile Garment")?.name === "Lebu Haile Garment",
);

// Spellings that differ between agents on the same street.
check(
  "Kasanchis is Kazanchis",
  findNeighbourhood("Kasanchis near ECA")?.name === "Kazanchis",
  `${findNeighbourhood("Kasanchis near ECA")?.name}`,
);
check(
  "Laga Tafo Abakiros is Laga Tafo",
  findNeighbourhood("Laga Tafo Abakiros")?.name === "Laga Tafo",
);
check("case does not matter", findNeighbourhood("bOlE aTlAs")?.name === "Bole Atlas");
check(
  "punctuation does not matter",
  findNeighbourhood("  Bole-Atlas,  ")?.name === "Bole Atlas",
);

// ---------------------------------------------------------------------------
// 4. Scatter stays inside the neighbourhood
//
// The offset exists so fifty markers are fifty clickable markers rather than
// one pile. It must not carry a property into the next district — at which
// point the label "approximate" would be a lie rather than a caveat.
// ---------------------------------------------------------------------------

const bole = findNeighbourhood("Bole")!;
const offsets = Array.from({ length: 200 }, (_, i) =>
  scatterWithin(bole, `DEMO-${i}`),
);

const metres = (a: { latitude: number; longitude: number }) => {
  const dLat = (a.latitude - bole.latitude) * 111_320;
  const dLon =
    (a.longitude - bole.longitude) *
    111_320 *
    Math.cos((bole.latitude * Math.PI) / 180);
  return Math.sqrt(dLat * dLat + dLon * dLon);
};

check(
  "every scattered point stays within the radius",
  offsets.every((point) => metres(point) <= SCATTER_RADIUS_M + 5),
  `${Math.max(...offsets.map(metres)).toFixed(0)} m`,
);
check(
  "and they are spread, not stacked on the centre",
  new Set(offsets.map((p) => `${p.latitude},${p.longitude}`)).size > 190,
  `${new Set(offsets.map((p) => `${p.latitude},${p.longitude}`)).size} distinct of 200`,
);

// The real constraint: scatter must be smaller than half the distance to the
// nearest *unrelated* neighbourhood, or a property drifts closer to the wrong
// area's centre than to its own.
//
// Pairs where one name contains the other are excluded, and that is not a
// convenience. Bole Medhanialem is 203 m from Bole because it is *in* Bole;
// Summit by Cambridge is inside Summit. A property scattered from the sub-area
// into its own parent district has not moved anywhere it does not belong. The
// pair that binds is Bole Imperial and Megenagna, which are genuinely
// different places.
const unrelated = (a: string, b: string) => {
  const x = a.toLowerCase();
  const y = b.toLowerCase();
  return !x.includes(y) && !y.includes(x);
};

let nearest = Infinity;
let nearestPair = "";
const places = knownNeighbourhoods();
for (let i = 0; i < places.length; i += 1) {
  for (let j = i + 1; j < places.length; j += 1) {
    const a = places[i]!;
    const b = places[j]!;
    if (!unrelated(a.name, b.name)) continue;
    const dLat = (a.latitude - b.latitude) * 111_320;
    const dLon =
      (a.longitude - b.longitude) * 111_320 * Math.cos((a.latitude * Math.PI) / 180);
    const distance = Math.sqrt(dLat * dLat + dLon * dLon);
    if (distance < nearest) {
      nearest = distance;
      nearestPair = `${a.name} / ${b.name}`;
    }
  }
}
check(
  "the scatter radius is smaller than the gap to the nearest unrelated area",
  SCATTER_RADIUS_M < nearest / 2,
  `${nearestPair} are ${nearest.toFixed(0)} m apart, so the limit is ${(nearest / 2).toFixed(0)} m and the radius is ${SCATTER_RADIUS_M} m`,
);

check(
  "the same property lands in the same place every time",
  JSON.stringify(scatterWithin(bole, "DEMO-007")) ===
    JSON.stringify(scatterWithin(bole, "DEMO-007")),
);
check(
  "and two properties do not land on each other",
  JSON.stringify(scatterWithin(bole, "DEMO-007")) !==
    JSON.stringify(scatterWithin(bole, "DEMO-008")),
);

// ---------------------------------------------------------------------------
// 5. The two gazetteers agree
//
// The Python generator holds its own copy. Compared as text rather than
// imported, because that is the only way to read it from here — and it is the
// drift that matters, not the mechanism.
// ---------------------------------------------------------------------------

const generator = readFileSync("scripts/build-property-demo-seed.py", "utf8");

for (const place of knownNeighbourhoods()) {
  const line = `("${place.name}", ${place.latitude}, ${place.longitude})`;
  check(
    `${place.name} matches the seed generator`,
    generator.includes(line),
    `the Python copy disagrees, or is missing: ${line}`,
  );
}

const pythonNames = [...generator.matchAll(/^\s{4}\("([^"]+)",/gm)].map((m) => m[1]);
check(
  "the generator knows no place the application does not",
  pythonNames.every((name) =>
    knownNeighbourhoods().some((place) => place.name === name),
  ),
  pythonNames
    .filter((name) => !knownNeighbourhoods().some((p) => p.name === name))
    .join(", "),
);
check(
  "and the two lists are the same length",
  pythonNames.length === knownNeighbourhoods().length,
  `python ${pythonNames.length}, typescript ${knownNeighbourhoods().length}`,
);

// ---------------------------------------------------------------------------
// 6. Every location in the shipped dataset resolves
//
// If this fails, the seed silently drops properties off the map. It is checked
// against the committed CSV so a dataset revision cannot quietly reduce the
// count.
// ---------------------------------------------------------------------------

const csv = readFileSync(
  "supabase/seed/property-demo/medosha_50_demo_properties.csv",
  "utf8",
);
const rows = csv.split("\n").slice(1).filter((line) => line.trim().length > 0);

check("the dataset still holds fifty properties", rows.length === 50, `${rows.length}`);

let unlocatable = 0;
for (const row of rows) {
  const match = row.match(
    /^[^,]*,(?:"[^"]*"|[^,]*),(?:"[^"]*"|[^,]*),("[^"]*"|[^,]*),/,
  );
  const location = (match?.[1] ?? "").replace(/^"|"$/g, "");
  if (!findNeighbourhood(location)) unlocatable += 1;
}
check(
  "every one of them can be placed",
  unlocatable === 0,
  `${unlocatable} would appear in the list with no pin`,
);

// ---------------------------------------------------------------------------
// 7. A demo listing says so, and never says it is verified
// ---------------------------------------------------------------------------

const demoBadges = listingBadges({
  sellerKind: "agent",
  listingVerified: false,
  sellerVerified: false,
  isPremium: false,
  isSample: true,
});

check("a sample listing carries a badge", demoBadges.some((b) => b.id === "demo"));
check(
  "and it is the first thing read",
  demoBadges[0]?.id === "demo",
  `${demoBadges[0]?.id}`,
);
check("it reads DEMO", demoBadges[0]?.label === "DEMO", demoBadges[0]?.label);
check(
  "and it explains itself on hover",
  (demoBadges[0]?.title.length ?? 0) > 20 &&
    demoBadges[0]!.title.toLowerCase().includes("not a real"),
  demoBadges[0]?.title,
);

const realBadges = listingBadges({
  sellerKind: "agent",
  listingVerified: true,
  sellerVerified: true,
  isPremium: true,
});
check(
  "a real listing carries no demo badge",
  !realBadges.some((b) => b.id === "demo"),
);
check(
  "and its own badges are untouched",
  realBadges.some((b) => b.id === "listing-verified") &&
    realBadges.some((b) => b.id === "seller-verified") &&
    realBadges.some((b) => b.id === "premium"),
  realBadges.map((b) => b.id).join(","),
);

// The database refuses the combination (0043), but a caller can still pass it,
// and what it renders then is worth pinning down.
const contradiction = listingBadges({
  sellerKind: "agent",
  listingVerified: true,
  sellerVerified: false,
  isPremium: false,
  isSample: true,
});
check(
  "a sample marked verified still leads with DEMO",
  contradiction[0]?.id === "demo",
  contradiction.map((b) => b.id).join(","),
);

// ---------------------------------------------------------------------------
// 8. An image that cannot be rendered must not take the page down
//
// `next/image` throws on a host outside `remotePatterns`, and a throw in a
// client component takes the route with it. Fifty demo listings carrying an
// unsplash URL turned the property map into "The map could not start" — the
// map, the listings, the filters and the search, lost to a thumbnail.
//
// The listing form has a cover-image URL box, so this is reachable by typing.
// ---------------------------------------------------------------------------

const RENDERABLE: [string | null, boolean][] = [
  // The one that caused the outage.
  ["https://images.unsplash.com/photo-1600607687920?w=1200", false],
  ["https://abc123.supabase.co/storage/v1/object/public/property-images/a/b.webp", true],
  ["https://evil.example.com/x.png", false],
  // A lookalike host: the check must compare hostnames, not search for a
  // substring, or `abc123.supabase.co.evil.com` would pass.
  ["https://abc123.supabase.co.evil.com/x.png", false],
  ["http://abc123.supabase.co/x.png", false],
  ["/images/projects/residential.svg", true],
  ["data:image/png;base64,iVBORw0KGgo=", true],
  // A data URI that is not an image. `dangerouslyAllowSVG` is on in
  // next.config.ts, so the bar for what may be inlined has to stay at images.
  ["data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==", false],
  ["data:application/javascript,alert(1)", false],
  ["javascript:alert(1)", false],
  ["not a url at all", false],
  ["", false],
  [null, false],
];

for (const [src, allowed] of RENDERABLE) {
  check(
    `${allowed ? "renders" : "refuses"}: ${String(src).slice(0, 46) || "(empty)"}`,
    isRenderableSrc(src) === allowed,
  );
}

check(
  "a refused source falls back to a local placeholder",
  safeImageSrc("https://images.unsplash.com/x").startsWith("/images/"),
  safeImageSrc("https://images.unsplash.com/x"),
);
check(
  "and an allowed one is passed through untouched",
  safeImageSrc("/images/projects/residential.svg") === "/images/projects/residential.svg",
);

// Every property surface that renders an image must go through the guard.
//
// Found the hard way: the card and the hover card were guarded, the panel was
// not, and the panel is what the city explorer opens — so the same error came
// straight back from a component nobody had looked at. Checking the files
// rather than remembering them is the difference between fixing this once and
// fixing it once per component.
const IMAGE_SURFACES = [
  "src/components/property/property-card.tsx",
  "src/components/property/hover-card.tsx",
  "src/components/property/property-panel.tsx",
];

for (const file of IMAGE_SURFACES) {
  const source = readFileSync(file, "utf8");
  const rendersImages = source.includes("<Image");
  const guarded =
    source.includes("safeImageSrc") || source.includes("isRenderableSrc");
  check(
    `${file.split("/").pop()} guards its image sources`,
    !rendersImages || guarded,
    "it renders next/image without checking the source can be rendered",
  );
}

// The seed must not reintroduce them.
const seed = readFileSync("supabase/migrations/0044_property_demo_seed.sql", "utf8");
check(
  "the demo seed carries no remote image host",
  !/https?:\/\/[^']*\.(?:jpg|jpeg|png|webp)/i.test(seed) &&
    !seed.includes("images.unsplash.com"),
  "a remote image URL is back in the seed",
);
check(
  "and every demo cover is a local path",
  [...seed.matchAll(/'(\/images\/[^']+)'/g)].length >= 50,
  `${[...seed.matchAll(/'(\/images\/[^']+)'/g)].length} local image paths found`,
);

// ---------------------------------------------------------------------------
// 8b. The rental dataset
//
// A hundred rentals in the same table as the sales, reached by the same
// filters. What can go wrong quietly: a location the gazetteer does not know
// (the listing vanishes from the map), a property type the mapping misses (the
// listing vanishes entirely), or a missing price period (the card shows a
// monthly rent as if it were a purchase price).
// ---------------------------------------------------------------------------

const rentalCsv = readFileSync(
  "supabase/seed/rental-demo/medosha_100_demo_rentals.csv",
  "utf8",
);
const rentalRows = rentalCsv.split("\n").slice(1).filter((line) => line.trim());

check("the rental dataset still holds a hundred rows", rentalRows.length === 100,
  `${rentalRows.length}`);

const rentalLocations = new Set<string>();
const rentalTypes = new Set<string>();
for (const row of rentalRows) {
  const field = row.split(",");
  if (field[4]) rentalLocations.add(field[4].trim());
  if (field[3]) rentalTypes.add(field[3].trim().toLowerCase());
}

let unlocatableRentals = 0;
for (const location of rentalLocations) {
  if (!findNeighbourhood(location)) {
    unlocatableRentals += 1;
    check(`rental location "${location}" can be placed`, false);
  }
}
check(
  "every rental location can be placed",
  unlocatableRentals === 0,
  `${unlocatableRentals} of ${rentalLocations.size} would appear with no pin`,
);

// The generator's type map, read as text: a type it does not know is silently
// dropped from the seed, and a hundred rentals becoming eighty-three is not
// something anybody notices in a map full of pins.
const rentalGenerator = readFileSync("scripts/build-rental-demo-seed.py", "utf8");
for (const type of rentalTypes) {
  check(
    `the seed maps the "${type}" property type`,
    rentalGenerator.includes(`"${type}":`),
    "listings of this type are dropped from the seed",
  );
}

const rentalSeed = readFileSync("supabase/migrations/0047_rental_demo_seed.sql", "utf8");

// Comments stripped first. The seed explains in prose why the period matters,
// so a check for the literal passed against a file that had stopped setting it
// — the explanation outlived the behaviour.
const rentalSql = rentalSeed
  .split("\n")
  .filter((line) => !line.trimStart().startsWith("--"))
  .join("\n");

check(
  "every rental is a rent listing",
  rentalSql.includes("'rent',"),
  "listing_kind is not rent, so the rental filters will not find them",
);
check(
  "and carries a monthly period, so the card can say / month",
  /d\.price,\s*'month'/.test(rentalSql),
  "a monthly rent with no period reads as a purchase price",
);
check(
  "the rentals carry no remote image host",
  !rentalSeed.includes("unsplash") &&
    !/https?:\/\/[^']*\.(?:jpg|jpeg|png|webp)/i.test(rentalSeed),
);
check(
  "and reuse the property demo's agent namespace, not a new one",
  rentalGenerator.includes('NAMESPACE = "medosha:property-demo:"'),
  "a different namespace would create ten more agents with the same ten names",
);

// ---------------------------------------------------------------------------
// 9. The accuracy vocabulary
// ---------------------------------------------------------------------------

check(
  "the accuracy values match the enum in 0043",
  LOCATION_ACCURACIES.join(",") === "exact,approximate,unknown",
  LOCATION_ACCURACIES.join(","),
);
check("a known accuracy is recognised", isLocationAccuracy("approximate"));
check("an unknown one is not", !isLocationAccuracy("roughly"));
check(
  "the approximate note says it is not the exact property",
  APPROXIMATE_NOTE.toLowerCase().includes("not the exact"),
  APPROXIMATE_NOTE,
);

// ---------------------------------------------------------------------------

if (failures.length > 0) {
  console.log(`\n${RED}${failures.length} failed${RESET}`);
  for (const failure of failures) console.log(`  ${RED}✗${RESET} ${failure}`);
}

console.log(
  `\n${failures.length === 0 ? GREEN : RED}${passed} passed, ${failures.length} failed${RESET}` +
    `\n${DIM}map: the right neighbourhood, or no pin at all${RESET}\n`,
);

process.exit(failures.length === 0 ? 0 : 1);
