import type { FeedMedia, FeedPost } from "./types";

// Only the original seeded media IDs and URLs qualify; user uploads are preserved.
const samplePhotos: Record<string, { original: string; url: string; alt: string }> = {
  "36e9fd75-a8db-38da-c45e-48870a5f5b73": {"original": "/images/feed/property.svg", "url": "/images/feed/photos/prop_bole_3bed_0.webp", "alt": "AI-generated illustration: Apartment block in Bole"},
  "6fa009c4-f0eb-4d5e-db31-e18c8749fcec": {"original": "/images/feed/property.svg", "url": "/images/feed/photos/prop_cmc_villa_0.webp", "alt": "AI-generated illustration: Villa at CMC Michael"},
  "db5ef0be-55fe-3074-1c7e-3af2487c341c": {"original": "/images/feed/property.svg", "url": "/images/feed/photos/prop_legetafo_land_0.webp", "alt": "AI-generated illustration: Residential plot in Legetafo"},
  "84cd21d7-fa92-4d5e-5936-71f83d6d0c81": {"original": "/images/feed/property.svg", "url": "/images/feed/photos/prop_hawassa_rent_0.webp", "alt": "AI-generated illustration: Furnished flat in Hawassa"},
  "6777afd1-dfba-e3e5-6235-396f2af255ec": {"original": "/images/feed/property.svg", "url": "/images/feed/photos/prop_adama_shop_0.webp", "alt": "AI-generated illustration: Commercial shop unit in Adama"},
  "3c798daf-d5df-835e-4248-018963612798": {"original": "/images/feed/materials.svg", "url": "/images/feed/photos/mat_opc_cement_0.webp", "alt": "AI-generated illustration: Pallets of OPC cement"},
  "7e970e74-61b6-fcf2-bb14-bd51c9b706b4": {"original": "/images/feed/materials.svg", "url": "/images/feed/photos/mat_rebar_12_0.webp", "alt": "AI-generated illustration: Deformed reinforcement bar"},
  "fabd8f56-bb60-5488-3098-856776f654c5": {"original": "/images/feed/materials.svg", "url": "/images/feed/photos/mat_hcb_20_0.webp", "alt": "AI-generated illustration: Hollow concrete blocks curing"},
  "625856b9-10e4-7da1-a986-ede8fd0e3242": {"original": "/images/feed/materials.svg", "url": "/images/feed/photos/mat_sand_washed_0.webp", "alt": "AI-generated illustration: Washed river sand stockpile"},
  "09fbc99c-7b49-ec4b-0748-09f5d8caec20": {"original": "/images/feed/furniture.svg", "url": "/images/feed/photos/furn_zigba_dining_0.webp", "alt": "AI-generated illustration: Solid zigba dining table"},
  "1e7ab8e9-d6eb-6261-e98f-92f87b6d39a8": {"original": "/images/feed/furniture.svg", "url": "/images/feed/photos/furn_office_fitout_0.webp", "alt": "AI-generated illustration: Four-person workstation cluster"},
  "b5becae3-52f3-0e0e-eacd-2a344c882f63": {"original": "/images/feed/furniture.svg", "url": "/images/feed/photos/furn_bamboo_lounge_0.webp", "alt": "AI-generated illustration: Laminated bamboo lounge chair"},
  "752af954-fc41-23c8-06dd-c1d271e22ae2": {"original": "/images/feed/equipment.svg", "url": "/images/feed/photos/equip_excavator_0.webp", "alt": "AI-generated illustration: Twenty-ton tracked excavator"},
  "237986d4-0b1f-8e53-6612-3de6f36dbd90": {"original": "/images/feed/equipment.svg", "url": "/images/feed/photos/equip_tower_crane_0.webp", "alt": "AI-generated illustration: Tower crane on a city site"},
  "ffff0542-4da0-1de7-04fc-7a48fafb443e": {"original": "/images/feed/equipment.svg", "url": "/images/feed/photos/equip_concrete_pump_0.webp", "alt": "AI-generated illustration: Trailer-mounted concrete pump"},
  "5a38e8c5-7161-80f9-cf61-3ad9516dfef3": {"original": "/images/feed/progress.svg", "url": "/images/feed/photos/prog_ayat_slab_0.webp", "alt": "AI-generated illustration: Slab pour in progress at Ayat"},
  "4ab1435c-7564-3fd3-5930-20456e772303": {"original": "/images/feed/progress.svg", "url": "/images/feed/photos/prog_bahirdar_foundation_0.webp", "alt": "AI-generated illustration: Raft foundation reinforcement"},
  "703d33d1-d07e-7285-9a4d-4c7849c54ecd": {"original": "/images/feed/progress.svg", "url": "/images/feed/photos/prog_mekelle_blockwork_0.webp", "alt": "AI-generated illustration: Blockwork at second floor"},
  "36f37162-1a12-219b-67b1-f269694edbb7": {"original": "/images/feed/progress.svg", "url": "/images/feed/photos/prog_kiremt_planning_0.webp", "alt": "AI-generated illustration: Site sequencing around the rains"},
  "3e24140f-57f6-0352-5104-a1083f03644a": {"original": "/images/feed/handover.svg", "url": "/images/feed/photos/prog_jemo_handover_0.webp", "alt": "AI-generated illustration: Completed units ready for handover"},
  "818cbdd7-dca0-86c0-0603-36dc31ca169e": {"original": "/images/feed/architecture.svg", "url": "/images/feed/photos/arch_sululta_house_0.webp", "alt": "AI-generated illustration: Courtyard house in Sululta"},
  "5c487fdc-766b-968d-3e9f-f979b9cc8905": {"original": "/images/feed/architecture.svg", "url": "/images/feed/photos/arch_hawassa_clinic_0.webp", "alt": "AI-generated illustration: Naturally ventilated clinic in Hawassa"},
  "331616fc-fe8b-d0da-64ee-43cde60ef32a": {"original": "/images/feed/architecture.svg", "url": "/images/feed/photos/arch_piassa_facade_0.webp", "alt": "AI-generated illustration: Restored facade on Piassa"},
  "8b7211ad-b923-ca60-e014-33da19d69d21": {"original": "/images/feed/architecture.svg", "url": "/images/feed/photos/arch_adama_warehouse_0.webp", "alt": "AI-generated illustration: Steel portal frame warehouse"},
  "2cdbde23-e3b8-600e-d933-469cf27323c7": {"original": "/images/feed/interior.svg", "url": "/images/feed/photos/int_bole_apartment_0.webp", "alt": "AI-generated illustration: Renovated apartment interior in Bole"},
  "6a3a6ea2-db26-b55a-0ab9-d3cfc19e1801": {"original": "/images/feed/interior.svg", "url": "/images/feed/photos/int_cafe_kazanchis_0.webp", "alt": "AI-generated illustration: Coffee house interior in Kazanchis"},
  "fa3b4e14-f161-308e-48ea-ba9473a289f8": {"original": "/images/feed/interior.svg", "url": "/images/feed/photos/int_condo_storage_0.webp", "alt": "AI-generated illustration: Storage built into a condominium unit"},
  "dc8d438a-51eb-0ef0-912f-a057ea35da63": {"original": "/images/feed/ai-design.svg", "url": "/images/feed/photos/ai_living_room_0.webp", "alt": "AI-generated illustration: AI-generated living room redesign"},
  "965d2cbc-1834-3a2f-e400-06c47853579a": {"original": "/images/feed/ai-design.svg", "url": "/images/feed/photos/ai_facade_options_0.webp", "alt": "AI-generated illustration: AI-generated facade options"},
  "1a12123d-be6d-a76d-6a06-3adf96b6f5d5": {"original": "/images/feed/before.svg", "url": "/images/feed/photos/ba_gerji_villa_0.webp", "alt": "AI-generated illustration: The Gerji villa before renovation"},
  "b8f58a0b-53bb-63ce-6c91-14cf15c6b006": {"original": "/images/feed/after.svg", "url": "/images/feed/photos/ba_gerji_villa_1.webp", "alt": "AI-generated illustration: The Gerji villa after renovation"},
  "cf05ebe7-32cc-1845-5d40-dfcb83a88ff2": {"original": "/images/feed/before.svg", "url": "/images/feed/photos/ba_shop_front_0.webp", "alt": "AI-generated illustration: The shop front before"},
  "f82edbc9-a9f5-c6ff-3058-7fa48275475f": {"original": "/images/feed/after.svg", "url": "/images/feed/photos/ba_shop_front_1.webp", "alt": "AI-generated illustration: The shop front after"},
  "26fe26e1-0dbf-3175-e24a-e6d30d1163c2": {"original": "/images/feed/floor-plan.svg", "url": "/images/feed/photos/plan_g1_villa_0.webp", "alt": "AI-generated illustration: G+1 villa floor plan"},
  "b3fc79fc-c7de-348b-72d5-6a241987c9dc": {"original": "/images/feed/floor-plan.svg", "url": "/images/feed/photos/plan_condo_studio_0.webp", "alt": "AI-generated illustration: Measured plan of an IHDP studio"},
  "45c6186a-e5ad-0214-b81b-fa41f5660041": {"original": "/images/feed/boq.svg", "url": "/images/feed/photos/boq_g1_villa_0.webp", "alt": "AI-generated illustration: Bill of quantities spreadsheet"},
  "5b81e02e-11b0-9e94-a39d-84e5d5639349": {"original": "/images/feed/boq.svg", "url": "/images/feed/photos/boq_finishing_0.webp", "alt": "AI-generated illustration: Finishing works bill of quantities"},
  "9a00a669-c659-eee0-fcdd-5d3746077906": {"original": "/images/feed/cost.svg", "url": "/images/feed/photos/cost_rebar_waste_0.webp", "alt": "AI-generated illustration: Rebar cutting waste diagram"},
  "3654825f-a1b3-d92f-2f56-bbc213647564": {"original": "/images/feed/cost.svg", "url": "/images/feed/photos/cost_advance_payment_0.webp", "alt": "AI-generated illustration: Comparing tender preliminaries"},
  "629db9ec-512f-5cc0-f306-3c02b09cadb9": {"original": "/images/feed/cost.svg", "url": "/images/feed/photos/cost_import_timing_0.webp", "alt": "AI-generated illustration: Procurement lead time chart"},
  "fddbbb4a-64af-4816-d285-3f9451d8a453": {"original": "/images/feed/price.svg", "url": "/images/feed/photos/price_cement_week_0.webp", "alt": "AI-generated illustration: Cement price movement"},
  "09cc08e6-27a2-bf2d-8821-19b91da9cfee": {"original": "/images/feed/price.svg", "url": "/images/feed/photos/price_rebar_down_0.webp", "alt": "AI-generated illustration: Rebar price movement"},
  "a960226e-dc3c-d700-e55e-ccfd85b657af": {"original": "/images/feed/price.svg", "url": "/images/feed/photos/price_hcb_stable_0.webp", "alt": "AI-generated illustration: Block price holding steady"},
  "493362fe-7b05-8e91-02d1-23abb1d6982a": {"original": "/images/feed/video.svg", "url": "/images/feed/photos/vid_slab_pour_0.webp", "alt": "AI-generated illustration: Time-lapse of a slab pour"},
  "fd4aee01-6d6f-63ba-2b10-4dd99e4abd4f": {"original": "/images/feed/video.svg", "url": "/images/feed/photos/vid_rebar_tying_0.webp", "alt": "AI-generated illustration: Column reinforcement in real time"},
  "6f52a7f4-8942-7c84-346f-fe94c44d5d1c": {"original": "/images/feed/video.svg", "url": "/images/feed/photos/vid_terrazzo_0.webp", "alt": "AI-generated illustration: Terrazzo poured and ground in situ"},
  "682571b4-83f3-e0e9-e716-f82e76c692fa": {"original": "/images/feed/tutorial.svg", "url": "/images/feed/photos/tut_concrete_cubes_0.webp", "alt": "AI-generated illustration: Taking concrete cube samples"},
  "a19d70b6-6ea7-998c-0591-8ad8cff3ea99": {"original": "/images/feed/tutorial.svg", "url": "/images/feed/photos/tut_setting_out_0.webp", "alt": "AI-generated illustration: Setting out with profile boards"},
  "9d52b333-f8a9-af22-408f-bb32e6316ad6": {"original": "/images/feed/tutorial.svg", "url": "/images/feed/photos/tut_earthing_0.webp", "alt": "AI-generated illustration: Residential earthing arrangement"},
  "a782c3c3-cd2a-0c41-4f41-32061da26bad": {"original": "/images/feed/model-3d.svg", "url": "/images/feed/photos/doc_revit_families_0.webp", "alt": "AI-generated illustration: Revit families for Ethiopian components"},
  "b9ea0184-ce44-64be-20ca-f216cbb1ca57": {"original": "/images/feed/cad.svg", "url": "/images/feed/photos/doc_cad_details_0.webp", "alt": "AI-generated illustration: Reinforced concrete CAD details"},
  "79b862cc-d816-c69f-015e-27b5aba8a28a": {"original": "/images/feed/model-3d.svg", "url": "/images/feed/photos/doc_sketchup_models_0.webp", "alt": "AI-generated illustration: SketchUp models of vernacular elements"},
  "0d43b5c9-b9b4-3472-4e52-c954970f31e5": {"original": "/images/feed/announcement.svg", "url": "/images/feed/photos/ann_gojo_hiring_0.webp", "alt": "AI-generated illustration: Hiring announcement"},
  "70d8a939-162b-a44a-90c8-d10b143a2534": {"original": "/images/feed/announcement.svg", "url": "/images/feed/photos/ann_abay_yard_0.webp", "alt": "AI-generated illustration: New cutting and bending yard"},
  "735c4fd7-1559-d61c-3b5a-89c840f63fbb": {"original": "/images/feed/professional.svg", "url": "/images/feed/photos/pro_tigist_0.webp", "alt": "AI-generated illustration: Professional profile"},
  "d6b8fa17-345c-4467-de75-a43e57a8399d": {"original": "/images/feed/professional.svg", "url": "/images/feed/photos/pro_solomon_0.webp", "alt": "AI-generated illustration: Professional profile"},
  "61fc103f-d2ae-0348-979c-985d49e5fd45": {"original": "/images/feed/investment.svg", "url": "/images/feed/photos/inv_entoto_block_0.webp", "alt": "AI-generated illustration: Demonstration investment project"},
  "41896677-6b11-36b8-81dc-9a71562fa4cd": {"original": "/images/feed/investment.svg", "url": "/images/feed/photos/inv_how_roi_works_0.webp", "alt": "AI-generated illustration: How a construction return is calculated"},
  "21702dd3-7fa9-10ee-5559-84cc0d6f72a7": {"original": "/images/feed/question.svg", "url": "/images/feed/photos/q_slab_crack_0.webp", "alt": "AI-generated illustration: Hairline cracks on a young slab"},
  "8fb79ab8-293d-21bd-0b84-7ee74001f47e": {"original": "/images/feed/question.svg", "url": "/images/feed/photos/q_hcb_vs_brick_0.webp", "alt": "AI-generated illustration: Choosing between block and brick"},
  "7d7edd7e-ee5f-de1a-2e97-a8c912b3f234": {"original": "/images/feed/question.svg", "url": "/images/feed/photos/q_title_transfer_0.webp", "alt": "AI-generated illustration: Title transfer timelines"},
  "b7925073-3b5b-79c0-e3a1-c3256167b42f": {"original": "/images/feed/discussion.svg", "url": "/images/feed/photos/disc_eucalyptus_scaffold_0.webp", "alt": "AI-generated illustration: Eucalyptus scaffolding on a site"},
  "b8f755fb-4cdf-2472-83a3-2aa562519304": {"original": "/images/feed/discussion.svg", "url": "/images/feed/photos/disc_corridor_development_0.webp", "alt": "AI-generated illustration: Street works and neighbouring sites"},
  "0973a0d5-8dd3-0508-65f8-03c8ead04d48": {"original": "/images/feed/course.svg", "url": "/images/feed/photos/learn_boq_course_0.webp", "alt": "AI-generated illustration: Free course on bills of quantities"},
  "80e27077-7a94-5728-0ed7-9c4557609fc0": {"original": "/images/feed/course.svg", "url": "/images/feed/photos/learn_ebcs_intro_0.webp", "alt": "AI-generated illustration: Free course on EBCS"},
  "ec2fbde3-39ed-bd08-d045-cceb1072e945": {"original": "/images/feed/course.svg", "url": "/images/feed/photos/learn_site_safety_0.webp", "alt": "AI-generated illustration: Free course on site safety"},
  "87e24caf-84cb-9a4c-a67f-83d1daba8377": {"original": "/images/feed/success.svg", "url": "/images/feed/photos/succ_workshop_to_factory_0.webp", "alt": "AI-generated illustration: From workshop to joinery business"},
  "4256cbf9-7da6-a81c-33f7-0b887a801242": {"original": "/images/feed/success.svg", "url": "/images/feed/photos/succ_first_building_0.webp", "alt": "AI-generated illustration: A first completed building"},
};

export function samplePostMedia(post: Pick<FeedPost, "isDemo" | "media">): FeedMedia[] {
  if (!post.isDemo) return post.media;
  return post.media.map((media) => {
    const photo = samplePhotos[media.id];
    if (!photo || media.kind !== "image" || media.url !== photo.original) return media;
    return { ...media, url: photo.url, alt: photo.alt, width: 1200, height: 900 };
  });
}
