-- Twenty tradespeople and eight firms, in the professionals directory.
--
-- Generated by scripts/build_professionals_seed.py. Do not edit by hand:
-- regenerate it, so the file and the roster cannot drift apart.
--
--   20 individual workers, 8 companies.
--   Every one of them has a trade, a base area and the areas they travel to,
--   so every one of them is findable by trade, findable by job location, and
--   drawable on the map.
--
-- ## Why Find Professionals was empty without this
--
-- The search matches on *where the job is*, through
-- `professional_service_areas`. A profile with no rows in that table matches
-- no area search at all, and `mapPoints` cannot place it either, because it
-- resolves a point from the name of an area and there is no name. So a
-- directory of profiles that had never filled that section in was a directory
-- that answered "nobody works here" for every area in the city and drew an
-- empty map. These rows are the first set that answers.
--
-- ## What is deliberately missing
--
-- **A phone number.** Not an oversight and not a placeholder. A plausible
-- +251 mobile number is a real handset belonging to a real person, and
-- publishing twenty-eight of them against fictional tradespeople would send
-- strangers' phones calls about rebar and roofing. `phone` stays null and
-- `show_phone` stays false, so the contact buttons use the platform's own
-- message and quote flow.
--
-- **Reviews and ratings.** A rating comes from `reviews`, and a seeded review
-- is a testimonial from somebody who does not exist about work that never
-- happened. These profiles carry years of experience, which is a claim, and no
-- rating, which is a fact nobody has yet established.
--
-- **`is_demo`.** Deliberately NOT set, and this is the trap worth naming:
-- `search_professionals` filters on `coalesce(p.is_demo, false) = false`, so
-- flagging these rows the way 0044 flags its demo agents would make every one
-- of them invisible to the only page that looks for them. Removability comes
-- from `seed_content` instead, which is a register the application never
-- reads — which is exactly what 0036 created it for.
--
-- Idempotent. Ids are derived from each username through a fixed namespace, so
-- re-running inserts nothing new. Removable: every row is registered in
-- `seed_content` under the batch 'professionals-2026-09', and the footer has the delete.
--
-- Additive. Run after 0078.

begin;

-- ---------------------------------------------------------------------------
-- Refuse to run against a schema that cannot hold this
-- ---------------------------------------------------------------------------

do $$
begin
  if to_regclass('public.professional_service_areas') is null
     or not exists (
       select 1 from information_schema.columns
       where table_schema = 'public' and table_name = 'profiles'
         and column_name = 'profession'
     ) then
    raise exception using
      message = 'Professionals seed: the service-area columns are missing.',
      hint = 'Run migration 0078 first.';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- The accounts
--
-- Inserted into auth.users, which fires the trigger from 0001 and creates the
-- profile. Writing to public.profiles directly would leave rows that no
-- foreign key from auth protects and that nobody could ever sign into.
--
-- No password and no confirmed email, so none of these can be signed in as.
-- ---------------------------------------------------------------------------

insert into auth.users (id, email)
values
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'tesfaye_alemu@professionals.medosha.local'),
  ('49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'yohannes_bekele@professionals.medosha.local'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'girma_tadesse@professionals.medosha.local'),
  ('8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'hiwot_mulugeta@professionals.medosha.local'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'solomon_desta@professionals.medosha.local'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'mekonnen_haile@professionals.medosha.local'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'getachew_assefa@professionals.medosha.local'),
  ('3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'dereje_wolde@professionals.medosha.local'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'ashenafi_negash@professionals.medosha.local'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'bekele_terefe@professionals.medosha.local'),
  ('5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'selamawit_girma@professionals.medosha.local'),
  ('b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'habtamu_regassa@professionals.medosha.local'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'almaz_hailu@professionals.medosha.local'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'fikadu_yimer@professionals.medosha.local'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'endale_mamo@professionals.medosha.local'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'meseret_legesse@professionals.medosha.local'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'alemayehu_tesfa@professionals.medosha.local'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'tigist_abera@professionals.medosha.local'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'muluken_bogale@professionals.medosha.local'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'birhanu_kassa@professionals.medosha.local'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'gerji_wood_works@professionals.medosha.local'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'kazanchis_electrical@professionals.medosha.local'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'lebu_metal_works@professionals.medosha.local'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'summit_interiors@professionals.medosha.local'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'kolfe_scaffolding@professionals.medosha.local'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'gotera_plumbing@professionals.medosha.local'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'shola_gypsum@professionals.medosha.local'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'lideta_contractors@professionals.medosha.local')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- The tradespeople
--
-- `travel_radius_km` is left null on purpose: these people listed the areas
-- they work in, and a radius on top of that would quietly add areas nobody
-- named. The listed areas are the claim.
-- ---------------------------------------------------------------------------

update public.profiles p
set full_name = s.full_name,
    username = s.username,
    account_type = 'individual',
    profession = s.profession,
    specialties = s.specialties,
    base_area = s.base_area,
    location_city = 'Addis Ababa',
    location_country = 'Ethiopia',
    years_experience = s.years_experience,
    work_status = s.work_status::public.work_status,
    bio = s.bio,
    serves_entire_city = false,
    travel_radius_km = null,
    show_phone = false,
    phone = null,
    onboarding_completed = true,
    updated_at = now()
from (values
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'Tesfaye Alemu', 'tesfaye_alemu', 'Carpenter', array['Doors', 'Cabinets', 'Roof timber']::text[], 'Gerji', 14, 'available', 'Doors, fitted cupboards and roof timber. Works from a small shop in Gerji and takes site work anywhere along the eastern side of the city.'),
  ('49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'Yohannes Bekele', 'yohannes_bekele', 'Carpenter''s Helper', array['Formwork', 'Shuttering', 'Sanding']::text[], 'Kotebe', 3, 'available', 'Three years on formwork and shuttering. Available by the day or by the week, and will travel to a site anywhere in Yeka.'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'Girma Tadesse', 'girma_tadesse', 'Electrician', array['House wiring', 'Distribution boards', 'Fault finding']::text[], 'Megenagna', 11, 'limited', 'House wiring and distribution boards, new build and rewiring. Eleven years, most of it on residential work in Yeka and Bole.'),
  ('8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'Hiwot Mulugeta', 'hiwot_mulugeta', 'Electrician''s Helper', array['Conduit chasing', 'Pulling cable', 'Fixing boxes']::text[], 'Kolfe Keranyo', 2, 'available', 'Chasing, conduit and cable pulling. Two years on site, looking for steady work with an electrician in the west of the city.'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'Solomon Desta', 'solomon_desta', 'Rebar Bender (Ferayo)', array['Column cages', 'Beam reinforcement', 'Stirrups']::text[], 'Lebu', 9, 'available', 'Ferayo. Column cages, beams and stirrups, cut and bent on site. Nine years on G+4 and below around Lebu and Gofa.'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'Mekonnen Haile', 'mekonnen_haile', 'Rebar Bender (Ferayo)', array['Slab mesh', 'Footing bars', 'Bar cutting']::text[], 'Ayat', 16, 'busy', 'Sixteen years bending bar, mostly on apartment blocks out towards Ayat and Legetafo. Works with a crew of four when the job needs it.'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'Getachew Assefa', 'getachew_assefa', 'Mason', array['Block work', 'Plastering', 'Foundations']::text[], 'Gofa', 18, 'limited', 'Block work, plastering and foundations. Eighteen years, villas and small apartment buildings on the southern side of the city.'),
  ('3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'Dereje Wolde', 'dereje_wolde', 'Mason''s Helper', array['Mixing mortar', 'Carrying blocks', 'Curing']::text[], 'Alem Bank', 4, 'available', 'Four years helping masons — mortar, blocks and curing. Starts early and is happy with a long job rather than a day here and there.'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'Ashenafi Negash', 'ashenafi_negash', 'Welder', array['Gates', 'Handrails', 'Window frames']::text[], '22 Area', 12, 'available', 'Gates, handrails and window frames, measured on site and made in the workshop at 22. Twelve years at it.'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'Bekele Terefe', 'bekele_terefe', 'Plumber', array['Bathrooms', 'Water tanks', 'Leak repair']::text[], 'Kazanchis', 10, 'limited', 'Bathrooms, kitchens, tanks and pumps. Ten years, and does the awkward leak-finding jobs other people have given up on.'),
  ('5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'Selamawit Girma', 'selamawit_girma', 'Plumber''s Helper', array['Chasing walls', 'Carrying pipe', 'Fitting brackets']::text[], 'Gotera', 2, 'available', 'Two years assisting on bathroom and kitchen installations. Chasing, pipe work and brackets.'),
  ('b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'Habtamu Regassa', 'habtamu_regassa', 'Construction Labourer', array['Concrete pouring', 'Loading and unloading', 'Site clean-up']::text[], 'Lebu Haile Garment', 6, 'available', 'Six years of general site labour — pours, loading, clearing. Reliable for a full week rather than a single day.'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'Almaz Hailu', 'almaz_hailu', 'Construction Labourer', array['Excavation by hand', 'Demolition', 'Site clean-up']::text[], 'Abinet', 5, 'available', 'Hand excavation, strip-out and clearing. Five years, and works with the same three people so a crew can be arranged at short notice.'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'Fikadu Yimer', 'fikadu_yimer', 'Scaffolder', array['Eucalyptus scaffold', 'Erecting', 'Edge protection']::text[], 'Shola', 8, 'limited', 'Eucalyptus and tube scaffold, erected and struck. Eight years, and will not leave a lift without edge protection on it.'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'Endale Mamo', 'endale_mamo', 'Roofer', array['Corrugated sheet', 'Purlins', 'Gutters and downpipes']::text[], 'Summit', 13, 'available', 'Corrugated roofing, purlins, gutters and downpipes. Thirteen years, and does leak repairs on roofs somebody else put up.'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'Meseret Legesse', 'meseret_legesse', 'Painter', array['Interior painting', 'Exterior painting', 'Decorative finishes']::text[], 'Bole Bulbula', 7, 'available', 'Interior and exterior painting, including the preparation nobody wants to do. Seven years, mostly apartments in Bole.'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'Alemayehu Tesfa', 'alemayehu_tesfa', 'Tile Installer', array['Floor tiling', 'Bathrooms', 'Granite']::text[], 'Old Airport', 9, 'busy', 'Floor and wall tiling, bathrooms and granite worktops. Nine years, and sets out a room before cutting anything.'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'Tigist Abera', 'tigist_abera', 'Gypsum Worker', array['Ceilings', 'Cornices', 'Lighting coves']::text[], 'Kebena', 6, 'available', 'Gypsum ceilings, cornices and lighting coves. Six years on residential and small office fit-outs.'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'Muluken Bogale', 'muluken_bogale', 'Excavator Operator', array['Foundation digging', 'Trenching', 'Site levelling']::text[], 'Laga Tafo', 15, 'limited', 'Excavator operator — foundations, trenches and levelling. Fifteen years. Machine hire arranged separately.'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'Birhanu Kassa', 'birhanu_kassa', 'Aluminium Worker', array['Windows', 'Doors', 'Partitions']::text[], 'Bole Denbel', 11, 'available', 'Aluminium windows, doors and office partitions. Eleven years, measured and fitted, and repairs on frames already in place.')

) as s(id, full_name, username, profession, specialties, base_area,
         years_experience, work_status, bio)
where p.id = s.id;

-- ---------------------------------------------------------------------------
-- The firms
--
-- `serves_entire_city` is true for the two that genuinely work across Addis
-- Ababa and false for the rest. It is not a bigger version of a service area:
-- the search treats it as a match for every area in the city, so a firm that
-- sets it and does not mean it sits in every result in the directory.
-- ---------------------------------------------------------------------------

update public.profiles p
set company_name = s.company_name,
    full_name = s.company_name,
    username = s.username,
    account_type = s.account_type::public.account_type,
    profession = s.profession,
    specialties = s.specialties,
    base_area = s.base_area,
    location_city = 'Addis Ababa',
    location_country = 'Ethiopia',
    years_experience = s.years_experience,
    work_status = s.work_status::public.work_status,
    bio = s.bio,
    serves_entire_city = s.serves_entire_city,
    travel_radius_km = null,
    show_phone = false,
    phone = null,
    onboarding_completed = true,
    updated_at = now()
from (values
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'Gerji Wood Works', 'gerji_wood_works', 'company', 'Furniture Maker', array['Kitchens', 'Wardrobes', 'Office furniture']::text[], 'Gerji', false, 9, 'available', 'Kitchens, wardrobes and office furniture, made in the workshop in Gerji and fitted on site. Fourteen people, nine years in business.'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Kazanchis Electrical Contractors', 'kazanchis_electrical', 'contractor', 'Electrician', array['House wiring', 'Distribution boards', 'Generators', 'Solar']::text[], 'Kazanchis', true, 12, 'limited', 'Electrical contracting for apartment blocks and offices: wiring, boards, generators and standby. Twelve years, and works across the city.'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Lebu Metal & Aluminium Works', 'lebu_metal_works', 'company', 'Aluminium Worker', array['Windows', 'Doors', 'Curtain walling', 'Shopfronts']::text[], 'Lebu', false, 7, 'available', 'Aluminium windows, curtain walling and shopfronts, plus steel gates and handrails. Own workshop at Lebu.'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'Summit Interiors & Fit-out', 'summit_interiors', 'company', 'Interior Designer', array['Offices', 'Cafés and restaurants', 'Furniture selection']::text[], 'Summit', false, 6, 'available', 'Office and restaurant fit-out from drawings through to handover. Small team, one project at a time.'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'Kolfe Scaffolding & Formwork', 'kolfe_scaffolding', 'company', 'Scaffolder', array['Tube and coupler', 'Erecting', 'Dismantling', 'Edge protection']::text[], 'Kolfe Keranyo', false, 10, 'limited', 'Scaffold and formwork hire with erection and striking included. Ten years supplying contractors on the western side of the city.'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Gotera Plumbing & Sanitary', 'gotera_plumbing', 'company', 'Plumber', array['Bathrooms', 'Kitchens', 'Water tanks', 'Pumps']::text[], 'Gotera', false, 8, 'available', 'Plumbing and sanitary installation for houses and small apartment buildings, including tanks and booster pumps.'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'Shola Gypsum & Ceiling', 'shola_gypsum', 'company', 'Gypsum Worker', array['Ceilings', 'Partitions', 'Cornices', 'Bulkheads']::text[], 'Shola', false, 5, 'available', 'Gypsum ceilings, partitions and bulkheads. Five years, mostly apartment finishing work in Yeka.'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Lideta Building Contractors', 'lideta_contractors', 'contractor', 'Contractor', array['Full build', 'Renovation', 'Site management', 'Finishing works']::text[], 'Lideta', true, 15, 'busy', 'General contracting: villas, G+4 residential and renovation. Fifteen years, sixty-four people, and works across Addis Ababa.')

) as s(id, company_name, username, account_type, profession, specialties,
         base_area, serves_entire_city, years_experience, work_status, bio)
where p.id = s.id;

-- ---------------------------------------------------------------------------
-- The areas each of them works in
--
-- Joined to location_areas by name rather than written with a slug beside it,
-- so an area this gazetteer does not have produces no row instead of a row
-- pointing at a slug that resolves to nothing. If a name below is ever
-- misspelled, that professional loses one area — it does not gain a broken one.
-- ---------------------------------------------------------------------------

insert into public.professional_service_areas (profile_id, area_slug, area_name, city, country)
select s.id, a.slug, a.name, a.city, a.country
from (values
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'Gerji'),
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'CMC'),
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'Bole'),
  ('4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'Summit'),
  ('49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'Kotebe'),
  ('49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'Ayat'),
  ('49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'Summit'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'Megenagna'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'Shola'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'Kazanchis'),
  ('6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'Bole'),
  ('8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'Kolfe Keranyo'),
  ('8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'Alem Bank'),
  ('8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'Lideta'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'Lebu'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'Lebu Haile Garment'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'Gofa'),
  ('2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'Sarbet'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'Ayat'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'Kotebe'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'Summit'),
  ('e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'Laga Tafo'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'Gofa'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'Sarbet'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'Old Airport'),
  ('f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'Meskel Flower'),
  ('3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'Alem Bank'),
  ('3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'Kolfe Keranyo'),
  ('3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'Abinet'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, '22 Area'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'Megenagna'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'Bole'),
  ('b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'Urael'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'Kazanchis'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'Kirkos'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'Mexico'),
  ('ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'Gotera'),
  ('5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'Gotera'),
  ('5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'Kirkos'),
  ('5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'Meskel Flower'),
  ('b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'Lebu'),
  ('b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'Lebu Haile Garment'),
  ('b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'Nifas Silk-Lafto'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'Abinet'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'Addisu Gebeya'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'Lideta'),
  ('1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'Ferensay'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'Shola'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'Megenagna'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'Yeka'),
  ('4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'Kebena'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'Summit'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'Summit by Cambridge'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'CMC'),
  ('19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'Ayat'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'Bole Bulbula'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'Bole'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'Bole Japan'),
  ('6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'Gerji'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'Old Airport'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'Sarbet'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'Gofa'),
  ('03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'Nifas Silk-Lafto'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'Kebena'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'Kazanchis'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'Ferensay'),
  ('5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'Yeka'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'Laga Tafo'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'Ayat'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'Kotebe'),
  ('4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'Summit'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'Bole Denbel'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'Bole Atlas'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'Bole Medhanialem'),
  ('9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'Urael'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'Gerji'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'CMC'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'Bole'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'Summit'),
  ('efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'Ayat'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Kazanchis'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Kirkos'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Mexico'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Bole'),
  ('183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'Megenagna'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Lebu'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Lebu Haile Garment'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Gofa'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Sarbet'),
  ('317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'Alem Bank'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'Summit'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'Summit by Cambridge'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'CMC'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'Bole'),
  ('3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'Gerji'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'Kolfe Keranyo'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'Alem Bank'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'Abinet'),
  ('fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'Lideta'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Gotera'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Kirkos'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Meskel Flower'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Kazanchis'),
  ('506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'Old Airport'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'Shola'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'Megenagna'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'Yeka'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'Kebena'),
  ('b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, '22 Area'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Lideta'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Abinet'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Mexico'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Kirkos'),
  ('a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'Addisu Gebeya')

) as s(id, area_name)
join public.location_areas a
  on lower(a.name) = lower(s.area_name) and a.city = 'Addis Ababa'
on conflict (profile_id, area_slug, city) do nothing;

-- ---------------------------------------------------------------------------
-- The firms, as businesses
--
-- A company on Medosha is two things: a profile somebody can hire through, and
-- a listing in the business directory. Creating only the first would leave
-- eight firms that answer a professional search and cannot be found by anybody
-- browsing companies, which is a difference nobody outside the schema would
-- expect.
--
-- `is_claimed` is true and `owner_id` points at the profile, because these are
-- not scraped listings waiting for somebody to claim them.
-- ---------------------------------------------------------------------------

insert into public.companies (
  slug, name, category, description, city, country,
  employees_count, owner_id, is_claimed, verified, import_source, external_ref
)
values
  ('gerji-wood-works', 'Gerji Wood Works', 'joinery', 'Kitchens, wardrobes and office furniture, made in the workshop in Gerji and fitted on site. Fourteen people, nine years in business.', 'Addis Ababa', 'Ethiopia', 14, 'efad828d-fc1d-5ced-849b-bf7074718098'::uuid, true, false, 'seed', 'gerji_wood_works'),
  ('kazanchis-electrical-contractors', 'Kazanchis Electrical Contractors', 'electrical', 'Electrical contracting for apartment blocks and offices: wiring, boards, generators and standby. Twelve years, and works across the city.', 'Addis Ababa', 'Ethiopia', 26, '183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, true, false, 'seed', 'kazanchis_electrical'),
  ('lebu-metal-&-aluminium-works', 'Lebu Metal & Aluminium Works', 'joinery', 'Aluminium windows, curtain walling and shopfronts, plus steel gates and handrails. Own workshop at Lebu.', 'Addis Ababa', 'Ethiopia', 18, '317736dd-036c-50bc-bfe3-6af399b78919'::uuid, true, false, 'seed', 'lebu_metal_works'),
  ('summit-interiors-&-fit-out', 'Summit Interiors & Fit-out', 'interior', 'Office and restaurant fit-out from drawings through to handover. Small team, one project at a time.', 'Addis Ababa', 'Ethiopia', 11, '3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, true, false, 'seed', 'summit_interiors'),
  ('kolfe-scaffolding-&-formwork', 'Kolfe Scaffolding & Formwork', 'general-contracting', 'Scaffold and formwork hire with erection and striking included. Ten years supplying contractors on the western side of the city.', 'Addis Ababa', 'Ethiopia', 32, 'fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, true, false, 'seed', 'kolfe_scaffolding'),
  ('gotera-plumbing-&-sanitary', 'Gotera Plumbing & Sanitary', 'plumbing', 'Plumbing and sanitary installation for houses and small apartment buildings, including tanks and booster pumps.', 'Addis Ababa', 'Ethiopia', 9, '506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, true, false, 'seed', 'gotera_plumbing'),
  ('shola-gypsum-&-ceiling', 'Shola Gypsum & Ceiling', 'finishing', 'Gypsum ceilings, partitions and bulkheads. Five years, mostly apartment finishing work in Yeka.', 'Addis Ababa', 'Ethiopia', 15, 'b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, true, false, 'seed', 'shola_gypsum'),
  ('lideta-building-contractors', 'Lideta Building Contractors', 'general-contracting', 'General contracting: villas, G+4 residential and renovation. Fifteen years, sixty-four people, and works across Addis Ababa.', 'Addis Ababa', 'Ethiopia', 64, 'a2227784-7113-5170-af22-a1b5b1637e17'::uuid, true, false, 'seed', 'lideta_contractors')
on conflict (import_source, external_ref) do nothing;

-- ---------------------------------------------------------------------------
-- The register
--
-- So this batch can be removed later, exactly, without anybody having to
-- remember which rows were which. Built from the ids this file wrote, not from
-- a flag on the row — a flag would have to be either read by the search (and
-- then it hides them) or ignored by it (and then it is not a flag, it is a
-- comment).
-- ---------------------------------------------------------------------------

insert into public.seed_content (entity, entity_id, batch)
values
  ('profiles', '4193d5fe-1f3f-5270-b174-a91ddfb2f99a'::uuid, 'professionals-2026-09'),
  ('profiles', '49d23c9c-ff2c-5286-bcf7-393c70937746'::uuid, 'professionals-2026-09'),
  ('profiles', '6cc46f88-de60-54ec-86ca-d54af762b405'::uuid, 'professionals-2026-09'),
  ('profiles', '8b93eeed-1060-5e8d-8ab4-9d287470fd09'::uuid, 'professionals-2026-09'),
  ('profiles', '2d461f1c-188a-5fde-8bd8-ad591d6995a8'::uuid, 'professionals-2026-09'),
  ('profiles', 'e44a1ee1-2db5-59bb-9b7b-e73561db8990'::uuid, 'professionals-2026-09'),
  ('profiles', 'f9b2ab4c-7f7a-57dd-a1e8-961e25ee8fde'::uuid, 'professionals-2026-09'),
  ('profiles', '3bf4b192-1731-5233-a5d4-9d6adfbcb396'::uuid, 'professionals-2026-09'),
  ('profiles', 'b19739ad-81d6-53a7-aa47-bfa00f5176ac'::uuid, 'professionals-2026-09'),
  ('profiles', 'ca328a23-98ec-543b-80f9-90141ae5d9a4'::uuid, 'professionals-2026-09'),
  ('profiles', '5f161016-c78e-5b77-a465-18098a35cfab'::uuid, 'professionals-2026-09'),
  ('profiles', 'b4a03b43-dea8-55a9-ba07-8105c7c22945'::uuid, 'professionals-2026-09'),
  ('profiles', '1d257b94-f23b-5596-8f68-b385cacce0dc'::uuid, 'professionals-2026-09'),
  ('profiles', '4afd1470-aecc-5558-a33c-55c8fd9f7cda'::uuid, 'professionals-2026-09'),
  ('profiles', '19f66b76-a15c-5f14-aaee-c51faf96129b'::uuid, 'professionals-2026-09'),
  ('profiles', '6f869af1-9bcd-531c-ba95-ad0ea471ada4'::uuid, 'professionals-2026-09'),
  ('profiles', '03dd7879-1dfb-55fa-8bfa-93ceed5dca4e'::uuid, 'professionals-2026-09'),
  ('profiles', '5dab3c2c-6ab8-50ce-9ca1-fc09a988b4a9'::uuid, 'professionals-2026-09'),
  ('profiles', '4525ea0d-fb15-5c25-b53c-afe6609cf0b4'::uuid, 'professionals-2026-09'),
  ('profiles', '9999023e-1dfb-5ebf-985a-3aa05d1d273b'::uuid, 'professionals-2026-09'),
  ('profiles', 'efad828d-fc1d-5ced-849b-bf7074718098'::uuid, 'professionals-2026-09'),
  ('profiles', '183ea4df-b3d7-510e-bb31-715d0a335077'::uuid, 'professionals-2026-09'),
  ('profiles', '317736dd-036c-50bc-bfe3-6af399b78919'::uuid, 'professionals-2026-09'),
  ('profiles', '3b6f39b9-d57d-556c-a6fe-8035c28e06ca'::uuid, 'professionals-2026-09'),
  ('profiles', 'fdb9878c-0214-5823-83ab-6c8bc36507c3'::uuid, 'professionals-2026-09'),
  ('profiles', '506f6981-1c9c-527b-8f79-cf7443ef92af'::uuid, 'professionals-2026-09'),
  ('profiles', 'b10b7d37-6c67-5aa1-84d2-37c3406981c1'::uuid, 'professionals-2026-09'),
  ('profiles', 'a2227784-7113-5170-af22-a1b5b1637e17'::uuid, 'professionals-2026-09')
on conflict (entity, entity_id) do nothing;

insert into public.seed_content (entity, entity_id, batch)
select 'companies', c.id, 'professionals-2026-09'
from public.companies c
where c.import_source = 'seed'
  and c.external_ref in ('gerji_wood_works', 'kazanchis_electrical', 'lebu_metal_works', 'summit_interiors', 'kolfe_scaffolding', 'gotera_plumbing', 'shola_gypsum', 'lideta_contractors')
on conflict (entity, entity_id) do nothing;

commit;

-- ---------------------------------------------------------------------------
-- To remove this batch entirely, run:
--
--   begin;
--   delete from public.companies
--    where id in (select entity_id from public.seed_content
--                  where batch = 'professionals-2026-09' and entity = 'companies');
--   delete from auth.users
--    where id in (select entity_id from public.seed_content
--                  where batch = 'professionals-2026-09' and entity = 'profiles');
--   delete from public.seed_content where batch = 'professionals-2026-09';
--   commit;
--
-- Deleting the auth user cascades to the profile, and the profile cascades to
-- its service areas. No real professional is touched: every id comes from the
-- register, and the register only ever held these rows.
-- ---------------------------------------------------------------------------
